version: '3.8'

services:
  duck-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./amplify:/app/amplify
    restart: unless-stopped
    stdin_open: true
    tty: true 